#!/usr/bin/env python3
"""
Generate future-agent handoff packet — explicit queue state for handoffs.

Usage:
    python generate-handoff-packet.py --output-dir ../../.handoff/

Creates .handoff/ packets containing:
- Current task state
- Dependencies and blockers
- Next steps (N>)
- Validation status
"""

import argparse
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any


@dataclass
class HandoffPacket:
    """Structured handoff packet for future agents."""
    
    # META section
    generated_at: str
    generator_version: str = "v1.6-research-ops"
    corpus_anchor: str = "R@{current}"
    
    # OBJ section
    objective: str = ""
    success_criteria: List[str] = field(default_factory=list)
    
    # C! section (constraints)
    hard_constraints: List[str] = field(default_factory=list)
    
    # D+ section (durable deltas landed)
    completed_work: List[str] = field(default_factory=list)
    
    # RK section (open risks)
    open_risks: List[str] = field(default_factory=list)
    
    # N> section (next steps)
    next_steps: List[str] = field(default_factory=list)
    
    # F[] section (file references)
    key_files: List[str] = field(default_factory=list)
    
    # V? section (validation)
    validation_status: str = "pending"
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, ensure_ascii=False)
    
    def to_md(self) -> str:
        """Generate human-readable markdown."""
        lines = [
            f"# Agent Handoff Packet",
            f"",
            f"**Generated**: {self.generated_at}",
            f"**Corpus**: {self.corpus_anchor}",
            f"",
            f"## Objective (OBJ)",
            f"",
            f"{self.objective}",
            f"",
        ]
        
        if self.success_criteria:
            lines.extend([
                f"### Success Criteria",
                f"",
            ])
            for sc in self.success_criteria:
                lines.append(f"- {sc}")
            lines.append("")
        
        if self.hard_constraints:
            lines.extend([
                f"## Hard Constraints (C!)",
                f"",
            ])
            for c in self.hard_constraints:
                lines.append(f"- {c}")
            lines.append("")
        
        if self.completed_work:
            lines.extend([
                f"## Completed Work (D+)",
                f"",
            ])
            for cw in self.completed_work:
                lines.append(f"- {cw}")
            lines.append("")
        
        if self.open_risks:
            lines.extend([
                f"## Open Risks (RK)",
                f"",
            ])
            for risk in self.open_risks:
                lines.append(f"- {risk}")
            lines.append("")
        
        if self.next_steps:
            lines.extend([
                f"## Next Steps (N>)",
                f"",
            ])
            for i, ns in enumerate(self.next_steps, 1):
                lines.append(f"{i}. {ns}")
            lines.append("")
        
        if self.key_files:
            lines.extend([
                f"## Key Files (F[])",
                f"",
            ])
            for f in self.key_files:
                lines.append(f"- `{f}`")
            lines.append("")
        
        lines.extend([
            f"## Validation Status (V?)",
            f"",
            f"{self.validation_status}",
            f"",
            f"---",
            f"",
            f"*This handoff packet was auto-generated by v1.6 research-ops tooling.*",
        ])
        
        return '\n'.join(lines)


def generate_v16_completion_packet() -> HandoffPacket:
    """Generate handoff packet for v1.6 completion state."""
    now = datetime.now().isoformat()[:10]  # YYYY-MM-DD
    
    packet = HandoffPacket(
        generated_at=now,
        corpus_anchor="R@{76-event corpus} B[Research] T[v1.6-research-ops]",
        objective="Complete v1.6 research-ops tooling for 76-event monograph-grade repo",
        success_criteria=[
            "Artifact completeness checks implemented",
            "Backlog hygiene monitoring active",
            "Discovery state integrity checks active",
            "Future-agent handoff support operational",
        ],
        hard_constraints=[
            "Tools remain read-only (docs canonical)",
            "No automated doc rewriting",
            "Human review required for all maintenance actions",
        ],
        completed_work=[
            "v1.5 analysis-ready tooling: 76-event corpus exports and validators",
            "Australia ledger: 18 events detailed (was 13, added 5)",
            "I/C/L/U metric companions auto-generated",
            "Cross-case pattern validation operational",
        ],
        open_risks=[
            "Implementation-observed marker counts differ from closure note prose",
            "Archive link decay not actively monitored (needs v1.7)",
        ],
        next_steps=[
            "Run research-ops tooling weekly to check drift",
            "Address any stale pending items in discovery logs",
            "Monitor surface freshness in docs/current-execution-order.md",
            "Consider v1.7 only if actual maintenance pain emerges",
        ],
        key_files=[
            "tools/exports/ledger-to-json.py",
            "tools/validators/validate-closure-note.py",
            "tools/generators/generate-metric-companions.py",
            "tools/research-ops/check-artifact-completeness.py",
            "tools/research-ops/check-backlog-hygiene.py",
            "tools/research-ops/check-discovery-state.py",
        ],
        validation_status="V+ (all v1.5 exit criteria met; v1.6 research-ops tooling implemented)",
    )
    
    return packet


def main():
    parser = argparse.ArgumentParser(
        description='Generate future-agent handoff packet'
    )
    parser.add_argument('--output-dir', '-o', type=Path,
                        default=Path('../../.handoff/'),
                        help='Output directory for handoff packets')
    parser.add_argument('--format', '-f', choices=['json', 'md'], default='md',
                        help='Output format')
    parser.add_argument('--name', '-n', default='v16-completion',
                        help='Packet name')
    args = parser.parse_args()
    
    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate packet
    packet = generate_v16_completion_packet()
    
    # Write output
    if args.format == 'json':
        output_path = args.output_dir / f"{args.name}.json"
        output_path.write_text(packet.to_json(), encoding='utf-8')
    else:
        output_path = args.output_dir / f"{args.name}.md"
        output_path.write_text(packet.to_md(), encoding='utf-8')
    
    print(f"Generated handoff packet: {output_path}")
    print(f"  Format: {args.format}")
    print(f"  Location: .handoff/{output_path.name}")
    print(f"\nPacket includes:")
    print(f"  - {len(packet.completed_work)} completed items")
    print(f"  - {len(packet.open_risks)} open risks")
    print(f"  - {len(packet.next_steps)} next steps")
    print(f"  - {len(packet.key_files)} key file references")


if __name__ == '__main__':
    main()
